services:
    PetitPress\GpsMessengerBundle\Transport\GpsTransportFactory:
        tags: [messenger.transport_factory]

    PetitPress\GpsMessengerBundle\Transport\GpsConfigurationResolver: ~
    PetitPress\GpsMessengerBundle\Transport\GpsConfigurationResolverInterface: '@PetitPress\GpsMessengerBundle\Transport\GpsConfigurationResolver'